#!/bin/sh

export PATH="/usr/local/sbin:$PATH";

# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

# Add usr/local/bin
export PATH="/usr/local/git/bin:/usr/local/bin:$PATH";

export PATH="/usr/local/opt/gettext/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.volta/bin:$PATH"
export PATH="$HOME/.mint/bin:$PATH"
export PATH="$HOME/.deno/bin:$PATH"

export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
